-- Create monthly_shares table to track percentage shares per month
CREATE TABLE IF NOT EXISTS public.monthly_shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    month_key TEXT NOT NULL, -- e.g., "2025-05" for May 2025
    percentage_share DECIMAL(5, 2) NOT NULL, -- e.g., 25.50 for 25.5%
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Foreign key constraint
    CONSTRAINT fk_person_monthly_share FOREIGN KEY (person_id) REFERENCES public.people(id) ON DELETE CASCADE,
    
    -- Unique constraint to ensure one percentage per person per month
    CONSTRAINT unique_person_month_share UNIQUE (person_id, month_key),
    
    -- Check constraint to ensure percentage is between 0 and 100
    CONSTRAINT check_percentage_range CHECK (percentage_share >= 0 AND percentage_share <= 100)
);

-- Grant permissions
GRANT ALL ON public.monthly_shares TO anon;
GRANT ALL ON public.monthly_shares_id_seq TO anon;

-- Create indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_monthly_shares_month_key ON public.monthly_shares(month_key);
CREATE INDEX IF NOT EXISTS idx_monthly_shares_person_id ON public.monthly_shares(person_id);