-- Create people table if it doesn't exist
create table if not exists public.people (
    id bigint generated by default as identity primary key,
    name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add foreign key constraint to expenses table
alter table public.expenses
add constraint fk_person
foreign key (person_id)
references public.people(id)
on delete set null;

-- Insert initial people data
insert into public.people (name)
values 
    ('Person 1'),
    ('Person 2'),
    ('Person 3'),
    ('Person 4'),
    ('Person 5')
on conflict (id) do nothing;

-- Grant necessary permissions
grant all on public.people to anon;
grant all on public.people_id_seq to anon;
