-- Create payments table to track settlement status
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_person_id BIGINT NOT NULL,
    to_person_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    month_key TEXT NOT NULL, -- e.g., "2024-12" or "overall"
    payment_key TEXT NOT NULL, -- unique identifier for the settlement
    paid BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Foreign key constraints
    CONSTRAINT fk_from_person FOREIGN KEY (from_person_id) REFERENCES public.people(id) ON DELETE CASCADE,
    CONSTRAINT fk_to_person FOREIGN KEY (to_person_id) REFERENCES public.people(id) ON DELETE CASCADE,
    
    -- Unique constraint to prevent duplicate payments for same settlement
    CONSTRAINT unique_payment_settlement UNIQUE (payment_key, month_key)
);

-- Grant permissions
GRANT ALL ON public.payments TO anon;
GRANT ALL ON public.payments_id_seq TO anon;

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_payments_month_key ON public.payments(month_key);
CREATE INDEX IF NOT EXISTS idx_payments_payment_key ON public.payments(payment_key);